export interface BusinessDef {
  id: string;
  name: string;
  emoji: string;
  color: string;
  baseIncome: number;
  baseTime: number; // seconds
  unlockCost: number;
  baseUpgradeCost: number;
  managerCost: number;
  description: string;
  managerName: string;
  managerBuff: number; // income multiplier when this manager is hired
  managerPerk: string; // short label shown on card
}

export const MILESTONES: Record<number, number> = {
  10: 2,
  25: 3,
  50: 5,
  100: 10,
  200: 15,
  300: 20,
  400: 25,
  500: 50,
};

export const BUSINESSES: BusinessDef[] = [
  {
    id: 'model3',
    name: 'Model 3 Factory',
    emoji: '🚗',
    color: '#E31937',
    baseIncome: 5,
    baseTime: 3,
    unlockCost: 0,
    baseUpgradeCost: 4,
    managerCost: 1000,
    description: 'The people\'s Tesla. Rolls off the line every few seconds.',
    managerName: 'Lars Moravy',
    managerBuff: 1.25,
    managerPerk: '+25% income',
  },
  {
    id: 'supercharger',
    name: 'Supercharger Station',
    emoji: '⚡',
    color: '#3E6AE1',
    baseIncome: 15,
    baseTime: 6,
    unlockCost: 150,
    baseUpgradeCost: 60,
    managerCost: 15000,
    description: '250 kW of pure juice. Road trip revenue.',
    managerName: 'Drew Baglino',
    managerBuff: 1.3,
    managerPerk: '+30% income',
  },
  {
    id: 'solarroof',
    name: 'Solar Roof Install',
    emoji: '🏠',
    color: '#ffd700',
    baseIncome: 50,
    baseTime: 12,
    unlockCost: 500,
    baseUpgradeCost: 720,
    managerCost: 100000,
    description: 'Turn every roof into a power plant.',
    managerName: 'Kunal Girotra',
    managerBuff: 1.35,
    managerPerk: '+35% income',
  },
  {
    id: 'powerwall',
    name: 'Powerwall Factory',
    emoji: '🔋',
    color: '#00c853',
    baseIncome: 120,
    baseTime: 20,
    unlockCost: 1500,
    baseUpgradeCost: 8640,
    managerCost: 500000,
    description: 'Store the sun. Sell the night.',
    managerName: 'JB Straubel',
    managerBuff: 1.4,
    managerPerk: '+40% income',
  },
  {
    id: 'modely',
    name: 'Model Y Line',
    emoji: '🚙',
    color: '#C0C0C0',
    baseIncome: 300,
    baseTime: 35,
    unlockCost: 4000,
    baseUpgradeCost: 103680,
    managerCost: 1200000,
    description: 'Best-selling car on the planet.',
    managerName: 'Rebecca Tinucci',
    managerBuff: 1.5,
    managerPerk: '+50% income',
  },
  {
    id: 'cybertruck',
    name: 'Cybertruck Plant',
    emoji: '🛻',
    color: '#9ca3af',
    baseIncome: 800,
    baseTime: 60,
    unlockCost: 12000,
    baseUpgradeCost: 1244160,
    managerCost: 10000000,
    description: 'Stainless steel, bulletproof glass, questionable angles.',
    managerName: 'Franz von Holzhausen',
    managerBuff: 1.6,
    managerPerk: '+60% income',
  },
  {
    id: 'semi',
    name: 'Semi Truck Hub',
    emoji: '🚛',
    color: '#64748b',
    baseIncome: 2000,
    baseTime: 120,
    unlockCost: 35000,
    baseUpgradeCost: 14929920,
    managerCost: 50000000,
    description: '500 miles on a charge. Freight reimagined.',
    managerName: 'Dan Priestley',
    managerBuff: 1.75,
    managerPerk: '+75% income',
  },
  {
    id: 'robotaxi',
    name: 'Robotaxi Fleet',
    emoji: '🤖',
    color: '#a855f7',
    baseIncome: 6000,
    baseTime: 300,
    unlockCost: 100000,
    baseUpgradeCost: 179159040,
    managerCost: 250000000,
    description: 'FSD meets ride-share. No driver, no problem.',
    managerName: 'Ashok Elluswamy',
    managerBuff: 2.0,
    managerPerk: '+100% income',
  },
  {
    id: 'optimus',
    name: 'Optimus Robot Factory',
    emoji: '🦾',
    color: '#f72585',
    baseIncome: 20000,
    baseTime: 720,
    unlockCost: 400000,
    baseUpgradeCost: 2149908480,
    managerCost: 1000000000,
    description: 'Humanoid workforce. Unlimited upside.',
    managerName: 'Milan Kovac',
    managerBuff: 2.5,
    managerPerk: '+150% income',
  },
  {
    id: 'mars',
    name: 'Mars Colony',
    emoji: '🚀',
    color: '#ef4444',
    baseIncome: 80000,
    baseTime: 1800,
    unlockCost: 2000000,
    baseUpgradeCost: 25798901760,
    managerCost: 5000000000,
    description: 'Occupy Mars. Monetize the stars.',
    managerName: 'Elon Musk',
    managerBuff: 3.0,
    managerPerk: '+200% income',
  },
];
